/*
 * This file is generated by jOOQ.
 */
package com.wuhainan.jooqblog;


import com.wuhainan.jooqblog.tables.Article;
import com.wuhainan.jooqblog.tables.Category;
import com.wuhainan.jooqblog.tables.Comment;
import com.wuhainan.jooqblog.tables.Tag;
import com.wuhainan.jooqblog.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blog extends SchemaImpl {

    private static final long serialVersionUID = 1695387343;

    /**
     * The reference instance of <code>blog</code>
     */
    public static final Blog BLOG = new Blog();

    /**
     * The table <code>blog.article</code>.
     */
    public final Article ARTICLE = com.wuhainan.jooqblog.tables.Article.ARTICLE;

    /**
     * The table <code>blog.category</code>.
     */
    public final Category CATEGORY = com.wuhainan.jooqblog.tables.Category.CATEGORY;

    /**
     * The table <code>blog.comment</code>.
     */
    public final Comment COMMENT = com.wuhainan.jooqblog.tables.Comment.COMMENT;

    /**
     * The table <code>blog.tag</code>.
     */
    public final Tag TAG = com.wuhainan.jooqblog.tables.Tag.TAG;

    /**
     * The table <code>blog.user</code>.
     */
    public final User USER = com.wuhainan.jooqblog.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Blog() {
        super("blog", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Article.ARTICLE,
            Category.CATEGORY,
            Comment.COMMENT,
            Tag.TAG,
            User.USER);
    }
}
