/*
 * This file is generated by jOOQ.
 */
package com.wuhainan.jooqblog;


import com.wuhainan.jooqblog.tables.Article;
import com.wuhainan.jooqblog.tables.Category;
import com.wuhainan.jooqblog.tables.Comment;
import com.wuhainan.jooqblog.tables.Tag;
import com.wuhainan.jooqblog.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in blog
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>blog.article</code>.
     */
    public static final Article ARTICLE = com.wuhainan.jooqblog.tables.Article.ARTICLE;

    /**
     * The table <code>blog.category</code>.
     */
    public static final Category CATEGORY = com.wuhainan.jooqblog.tables.Category.CATEGORY;

    /**
     * The table <code>blog.comment</code>.
     */
    public static final Comment COMMENT = com.wuhainan.jooqblog.tables.Comment.COMMENT;

    /**
     * The table <code>blog.tag</code>.
     */
    public static final Tag TAG = com.wuhainan.jooqblog.tables.Tag.TAG;

    /**
     * The table <code>blog.user</code>.
     */
    public static final User USER = com.wuhainan.jooqblog.tables.User.USER;
}
