/*
 * This file is generated by jOOQ.
 */
package com.wuhainan.jooqblog.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Article implements Serializable {

    private static final long serialVersionUID = -124408260;

    private String    id;
    private Timestamp createTime;
    private String    creatorId;
    private Integer   deleteStatus;
    private Timestamp deleteTime;
    private String    deleterId;
    private Timestamp lastEditTime;
    private String    lastEditorId;
    private Integer   version;
    private String    categoryId;
    private String    commentId;
    private String    content;
    private String    contentHtml;
    private String    summary;
    private String    tagId;
    private String    title;
    private Integer   topping;
    private Integer   viewCounts;

    public Article() {}

    public Article(Article value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.creatorId = value.creatorId;
        this.deleteStatus = value.deleteStatus;
        this.deleteTime = value.deleteTime;
        this.deleterId = value.deleterId;
        this.lastEditTime = value.lastEditTime;
        this.lastEditorId = value.lastEditorId;
        this.version = value.version;
        this.categoryId = value.categoryId;
        this.commentId = value.commentId;
        this.content = value.content;
        this.contentHtml = value.contentHtml;
        this.summary = value.summary;
        this.tagId = value.tagId;
        this.title = value.title;
        this.topping = value.topping;
        this.viewCounts = value.viewCounts;
    }

    public Article(
        String    id,
        Timestamp createTime,
        String    creatorId,
        Integer   deleteStatus,
        Timestamp deleteTime,
        String    deleterId,
        Timestamp lastEditTime,
        String    lastEditorId,
        Integer   version,
        String    categoryId,
        String    commentId,
        String    content,
        String    contentHtml,
        String    summary,
        String    tagId,
        String    title,
        Integer   topping,
        Integer   viewCounts
    ) {
        this.id = id;
        this.createTime = createTime;
        this.creatorId = creatorId;
        this.deleteStatus = deleteStatus;
        this.deleteTime = deleteTime;
        this.deleterId = deleterId;
        this.lastEditTime = lastEditTime;
        this.lastEditorId = lastEditorId;
        this.version = version;
        this.categoryId = categoryId;
        this.commentId = commentId;
        this.content = content;
        this.contentHtml = contentHtml;
        this.summary = summary;
        this.tagId = tagId;
        this.title = title;
        this.topping = topping;
        this.viewCounts = viewCounts;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public String getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    public Timestamp getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(Timestamp deleteTime) {
        this.deleteTime = deleteTime;
    }

    public String getDeleterId() {
        return this.deleterId;
    }

    public void setDeleterId(String deleterId) {
        this.deleterId = deleterId;
    }

    public Timestamp getLastEditTime() {
        return this.lastEditTime;
    }

    public void setLastEditTime(Timestamp lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    public String getLastEditorId() {
        return this.lastEditorId;
    }

    public void setLastEditorId(String lastEditorId) {
        this.lastEditorId = lastEditorId;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public String getCommentId() {
        return this.commentId;
    }

    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContentHtml() {
        return this.contentHtml;
    }

    public void setContentHtml(String contentHtml) {
        this.contentHtml = contentHtml;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getTagId() {
        return this.tagId;
    }

    public void setTagId(String tagId) {
        this.tagId = tagId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getTopping() {
        return this.topping;
    }

    public void setTopping(Integer topping) {
        this.topping = topping;
    }

    public Integer getViewCounts() {
        return this.viewCounts;
    }

    public void setViewCounts(Integer viewCounts) {
        this.viewCounts = viewCounts;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Article (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(creatorId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(deleterId);
        sb.append(", ").append(lastEditTime);
        sb.append(", ").append(lastEditorId);
        sb.append(", ").append(version);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(commentId);
        sb.append(", ").append(content);
        sb.append(", ").append(contentHtml);
        sb.append(", ").append(summary);
        sb.append(", ").append(tagId);
        sb.append(", ").append(title);
        sb.append(", ").append(topping);
        sb.append(", ").append(viewCounts);

        sb.append(")");
        return sb.toString();
    }
}
