/*
 * This file is generated by jOOQ.
 */
package com.wuhainan.jooqblog.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tag implements Serializable {

    private static final long serialVersionUID = 652421813;

    private String    id;
    private Timestamp createTime;
    private Integer   creatorId;
    private Integer   deleteStatus;
    private Timestamp deleteTime;
    private Integer   deleterId;
    private Timestamp lastEditTime;
    private Integer   lastEditorId;
    private Integer   version;
    private String    avatar;
    private String    tagName;

    public Tag() {}

    public Tag(Tag value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.creatorId = value.creatorId;
        this.deleteStatus = value.deleteStatus;
        this.deleteTime = value.deleteTime;
        this.deleterId = value.deleterId;
        this.lastEditTime = value.lastEditTime;
        this.lastEditorId = value.lastEditorId;
        this.version = value.version;
        this.avatar = value.avatar;
        this.tagName = value.tagName;
    }

    public Tag(
        String    id,
        Timestamp createTime,
        Integer   creatorId,
        Integer   deleteStatus,
        Timestamp deleteTime,
        Integer   deleterId,
        Timestamp lastEditTime,
        Integer   lastEditorId,
        Integer   version,
        String    avatar,
        String    tagName
    ) {
        this.id = id;
        this.createTime = createTime;
        this.creatorId = creatorId;
        this.deleteStatus = deleteStatus;
        this.deleteTime = deleteTime;
        this.deleterId = deleterId;
        this.lastEditTime = lastEditTime;
        this.lastEditorId = lastEditorId;
        this.version = version;
        this.avatar = avatar;
        this.tagName = tagName;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Integer getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    public Timestamp getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(Timestamp deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleterId() {
        return this.deleterId;
    }

    public void setDeleterId(Integer deleterId) {
        this.deleterId = deleterId;
    }

    public Timestamp getLastEditTime() {
        return this.lastEditTime;
    }

    public void setLastEditTime(Timestamp lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    public Integer getLastEditorId() {
        return this.lastEditorId;
    }

    public void setLastEditorId(Integer lastEditorId) {
        this.lastEditorId = lastEditorId;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getTagName() {
        return this.tagName;
    }

    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tag (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(creatorId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(deleterId);
        sb.append(", ").append(lastEditTime);
        sb.append(", ").append(lastEditorId);
        sb.append(", ").append(version);
        sb.append(", ").append(avatar);
        sb.append(", ").append(tagName);

        sb.append(")");
        return sb.toString();
    }
}
