/*
 * This file is generated by jOOQ.
 */
package com.wuhainan.jooqblog.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 494213458;

    private String    id;
    private Timestamp createTime;
    private Integer   creatorId;
    private Integer   deleteStatus;
    private Timestamp deleteTime;
    private Integer   deleterId;
    private Timestamp lastEditTime;
    private Integer   lastEditorId;
    private Integer   version;
    private Boolean   admin;
    private String    avatar;
    private String    cellphoneNumber;
    private String    email;
    private Timestamp lastLogin;
    private String    nickname;
    private String    password;
    private String    salt;
    private String    status;
    private String    username;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.creatorId = value.creatorId;
        this.deleteStatus = value.deleteStatus;
        this.deleteTime = value.deleteTime;
        this.deleterId = value.deleterId;
        this.lastEditTime = value.lastEditTime;
        this.lastEditorId = value.lastEditorId;
        this.version = value.version;
        this.admin = value.admin;
        this.avatar = value.avatar;
        this.cellphoneNumber = value.cellphoneNumber;
        this.email = value.email;
        this.lastLogin = value.lastLogin;
        this.nickname = value.nickname;
        this.password = value.password;
        this.salt = value.salt;
        this.status = value.status;
        this.username = value.username;
    }

    public User(
        String    id,
        Timestamp createTime,
        Integer   creatorId,
        Integer   deleteStatus,
        Timestamp deleteTime,
        Integer   deleterId,
        Timestamp lastEditTime,
        Integer   lastEditorId,
        Integer   version,
        Boolean   admin,
        String    avatar,
        String    cellphoneNumber,
        String    email,
        Timestamp lastLogin,
        String    nickname,
        String    password,
        String    salt,
        String    status,
        String    username
    ) {
        this.id = id;
        this.createTime = createTime;
        this.creatorId = creatorId;
        this.deleteStatus = deleteStatus;
        this.deleteTime = deleteTime;
        this.deleterId = deleterId;
        this.lastEditTime = lastEditTime;
        this.lastEditorId = lastEditorId;
        this.version = version;
        this.admin = admin;
        this.avatar = avatar;
        this.cellphoneNumber = cellphoneNumber;
        this.email = email;
        this.lastLogin = lastLogin;
        this.nickname = nickname;
        this.password = password;
        this.salt = salt;
        this.status = status;
        this.username = username;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Integer getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    public Integer getDeleteStatus() {
        return this.deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    public Timestamp getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(Timestamp deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleterId() {
        return this.deleterId;
    }

    public void setDeleterId(Integer deleterId) {
        this.deleterId = deleterId;
    }

    public Timestamp getLastEditTime() {
        return this.lastEditTime;
    }

    public void setLastEditTime(Timestamp lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    public Integer getLastEditorId() {
        return this.lastEditorId;
    }

    public void setLastEditorId(Integer lastEditorId) {
        this.lastEditorId = lastEditorId;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Boolean getAdmin() {
        return this.admin;
    }

    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getCellphoneNumber() {
        return this.cellphoneNumber;
    }

    public void setCellphoneNumber(String cellphoneNumber) {
        this.cellphoneNumber = cellphoneNumber;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Timestamp getLastLogin() {
        return this.lastLogin;
    }

    public void setLastLogin(Timestamp lastLogin) {
        this.lastLogin = lastLogin;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(creatorId);
        sb.append(", ").append(deleteStatus);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(deleterId);
        sb.append(", ").append(lastEditTime);
        sb.append(", ").append(lastEditorId);
        sb.append(", ").append(version);
        sb.append(", ").append(admin);
        sb.append(", ").append(avatar);
        sb.append(", ").append(cellphoneNumber);
        sb.append(", ").append(email);
        sb.append(", ").append(lastLogin);
        sb.append(", ").append(nickname);
        sb.append(", ").append(password);
        sb.append(", ").append(salt);
        sb.append(", ").append(status);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
