/*
 * This file is generated by jOOQ.
 */
package com.wuhainan.jooqblog.tables.daos;


import com.wuhainan.jooqblog.tables.Comment;
import com.wuhainan.jooqblog.tables.records.CommentRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentDao extends DAOImpl<CommentRecord, com.wuhainan.jooqblog.tables.pojos.Comment, String> {

    /**
     * Create a new CommentDao without any configuration
     */
    public CommentDao() {
        super(Comment.COMMENT, com.wuhainan.jooqblog.tables.pojos.Comment.class);
    }

    /**
     * Create a new CommentDao with an attached configuration
     */
    public CommentDao(Configuration configuration) {
        super(Comment.COMMENT, com.wuhainan.jooqblog.tables.pojos.Comment.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.wuhainan.jooqblog.tables.pojos.Comment object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchById(String... values) {
        return fetch(Comment.COMMENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wuhainan.jooqblog.tables.pojos.Comment fetchOneById(String value) {
        return fetchOne(Comment.COMMENT.ID, value);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByCreateTime(Timestamp... values) {
        return fetch(Comment.COMMENT.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>creator_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByCreatorId(Integer... values) {
        return fetch(Comment.COMMENT.CREATOR_ID, values);
    }

    /**
     * Fetch records that have <code>delete_status IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByDeleteStatus(Integer... values) {
        return fetch(Comment.COMMENT.DELETE_STATUS, values);
    }

    /**
     * Fetch records that have <code>delete_time IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByDeleteTime(Timestamp... values) {
        return fetch(Comment.COMMENT.DELETE_TIME, values);
    }

    /**
     * Fetch records that have <code>deleter_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByDeleterId(Integer... values) {
        return fetch(Comment.COMMENT.DELETER_ID, values);
    }

    /**
     * Fetch records that have <code>last_edit_time IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByLastEditTime(Timestamp... values) {
        return fetch(Comment.COMMENT.LAST_EDIT_TIME, values);
    }

    /**
     * Fetch records that have <code>last_editor_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByLastEditorId(Integer... values) {
        return fetch(Comment.COMMENT.LAST_EDITOR_ID, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByVersion(Integer... values) {
        return fetch(Comment.COMMENT.VERSION, values);
    }

    /**
     * Fetch records that have <code>children_ids IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByChildrenIds(String... values) {
        return fetch(Comment.COMMENT.CHILDREN_IDS, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByContent(String... values) {
        return fetch(Comment.COMMENT.CONTENT, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByParentId(String... values) {
        return fetch(Comment.COMMENT.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>to_user_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByToUserId(String... values) {
        return fetch(Comment.COMMENT.TO_USER_ID, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Comment> fetchByType(String... values) {
        return fetch(Comment.COMMENT.TYPE, values);
    }
}
