/*
 * This file is generated by jOOQ.
 */
package com.wuhainan.jooqblog.tables.daos;


import com.wuhainan.jooqblog.tables.Tag;
import com.wuhainan.jooqblog.tables.records.TagRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagDao extends DAOImpl<TagRecord, com.wuhainan.jooqblog.tables.pojos.Tag, String> {

    /**
     * Create a new TagDao without any configuration
     */
    public TagDao() {
        super(Tag.TAG, com.wuhainan.jooqblog.tables.pojos.Tag.class);
    }

    /**
     * Create a new TagDao with an attached configuration
     */
    public TagDao(Configuration configuration) {
        super(Tag.TAG, com.wuhainan.jooqblog.tables.pojos.Tag.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.wuhainan.jooqblog.tables.pojos.Tag object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchById(String... values) {
        return fetch(Tag.TAG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wuhainan.jooqblog.tables.pojos.Tag fetchOneById(String value) {
        return fetchOne(Tag.TAG.ID, value);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchByCreateTime(Timestamp... values) {
        return fetch(Tag.TAG.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>creator_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchByCreatorId(Integer... values) {
        return fetch(Tag.TAG.CREATOR_ID, values);
    }

    /**
     * Fetch records that have <code>delete_status IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchByDeleteStatus(Integer... values) {
        return fetch(Tag.TAG.DELETE_STATUS, values);
    }

    /**
     * Fetch records that have <code>delete_time IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchByDeleteTime(Timestamp... values) {
        return fetch(Tag.TAG.DELETE_TIME, values);
    }

    /**
     * Fetch records that have <code>deleter_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchByDeleterId(Integer... values) {
        return fetch(Tag.TAG.DELETER_ID, values);
    }

    /**
     * Fetch records that have <code>last_edit_time IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchByLastEditTime(Timestamp... values) {
        return fetch(Tag.TAG.LAST_EDIT_TIME, values);
    }

    /**
     * Fetch records that have <code>last_editor_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchByLastEditorId(Integer... values) {
        return fetch(Tag.TAG.LAST_EDITOR_ID, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchByVersion(Integer... values) {
        return fetch(Tag.TAG.VERSION, values);
    }

    /**
     * Fetch records that have <code>avatar IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchByAvatar(String... values) {
        return fetch(Tag.TAG.AVATAR, values);
    }

    /**
     * Fetch records that have <code>tag_name IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.Tag> fetchByTagName(String... values) {
        return fetch(Tag.TAG.TAG_NAME, values);
    }
}
