/*
 * This file is generated by jOOQ.
 */
package com.wuhainan.jooqblog.tables.daos;


import com.wuhainan.jooqblog.tables.User;
import com.wuhainan.jooqblog.tables.records.UserRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, com.wuhainan.jooqblog.tables.pojos.User, String> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, com.wuhainan.jooqblog.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, com.wuhainan.jooqblog.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.wuhainan.jooqblog.tables.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchById(String... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wuhainan.jooqblog.tables.pojos.User fetchOneById(String value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByCreateTime(Timestamp... values) {
        return fetch(User.USER.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>creator_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByCreatorId(Integer... values) {
        return fetch(User.USER.CREATOR_ID, values);
    }

    /**
     * Fetch records that have <code>delete_status IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByDeleteStatus(Integer... values) {
        return fetch(User.USER.DELETE_STATUS, values);
    }

    /**
     * Fetch records that have <code>delete_time IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByDeleteTime(Timestamp... values) {
        return fetch(User.USER.DELETE_TIME, values);
    }

    /**
     * Fetch records that have <code>deleter_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByDeleterId(Integer... values) {
        return fetch(User.USER.DELETER_ID, values);
    }

    /**
     * Fetch records that have <code>last_edit_time IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByLastEditTime(Timestamp... values) {
        return fetch(User.USER.LAST_EDIT_TIME, values);
    }

    /**
     * Fetch records that have <code>last_editor_id IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByLastEditorId(Integer... values) {
        return fetch(User.USER.LAST_EDITOR_ID, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByVersion(Integer... values) {
        return fetch(User.USER.VERSION, values);
    }

    /**
     * Fetch records that have <code>admin IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByAdmin(Boolean... values) {
        return fetch(User.USER.ADMIN, values);
    }

    /**
     * Fetch records that have <code>avatar IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByAvatar(String... values) {
        return fetch(User.USER.AVATAR, values);
    }

    /**
     * Fetch records that have <code>cellphone_number IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByCellphoneNumber(String... values) {
        return fetch(User.USER.CELLPHONE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByEmail(String... values) {
        return fetch(User.USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>last_login IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByLastLogin(Timestamp... values) {
        return fetch(User.USER.LAST_LOGIN, values);
    }

    /**
     * Fetch records that have <code>nickname IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByNickname(String... values) {
        return fetch(User.USER.NICKNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByPassword(String... values) {
        return fetch(User.USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>salt IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchBySalt(String... values) {
        return fetch(User.USER.SALT, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByStatus(String... values) {
        return fetch(User.USER.STATUS, values);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.wuhainan.jooqblog.tables.pojos.User> fetchByUsername(String... values) {
        return fetch(User.USER.USERNAME, values);
    }
}
